services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      - PORT=${PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_URL=${BOT_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
volumes:
  db_data:
