services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      - PORT=${PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_URL=${BOT_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis
  db:
      image: postgres:latest
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - db_data:/var/lib/postgresql/data
      ports:
        - ${DB_PORT}:${DB_PORT}

  redis:
      image: redis:latest
      ports:
        - ${REDIS_PORT}:${REDIS_PORT}
volumes:
  db_data:
